# Generated by Django 4.2.23 on 2026-05-25 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('np_sender_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('np_sender_address_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('np_sender_contact_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('np_sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
