# Generated by Django 4.2.23 on 2026-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(choices=[('nova_poshta', 'Нова пошта'), ('ukr_poshta', 'Укр пошта'), ('meest', 'Meest')], default='nova_poshta', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
