# Generated by Django 4.2.23 on 2026-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_branch_order_city_order_delivery_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('shipped', 'Надіслано'), ('delivered', 'Доставлено'), ('canceled', 'Скасовано')], default='pending', max_length=20),
        ),
    ]
