# Generated by Django 4.2.23 on 2026-05-17 12:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Значення знижки (в грн для фіксованої знижки)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Знижка у відсотках (для відсоткового типу)'),
        ),
    ]
