# Generated by Django 4.2.23 on 2026-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_coupon_discount_type_coupon_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою'), ('cod', 'Накладений платіж'), ('partial', 'Внесок 10% від вартості товару')], default='card', max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
