# Generated by Django 4.2.23 on 2026-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='АКЦІЯ', help_text="Наприклад: 'АКЦІЯ' або 'NEW ARRIVAL'", max_length=50, verbose_name='Текст бейджа')),
                ('badge_class', models.CharField(choices=[('bg-primary', 'Primary (Синій)'), ('bg-info text-dark', 'Info (Блакитний)'), ('bg-danger', 'Danger (Червоний)'), ('bg-warning text-dark', 'Warning (Жовтий)'), ('bg-success', 'Success (Зелений)')], default='bg-primary', max_length=50, verbose_name='Стиль бейджа (Bootstrap)')),
                ('title', models.CharField(help_text="Наприклад: 'Нова ера геймінгу:' або 'Легендарний дизайн'", max_length=250, verbose_name='Головний заголовок')),
                ('title_highlight', models.CharField(blank=True, help_text="Частина заголовка, що буде світитися синім кольором. Наприклад: 'HP Victus серія' або 'iPhone 12'", max_length=200, verbose_name='Виділена частина заголовка (сяйво)')),
                ('description', models.TextField(blank=True, help_text='Короткий опис пропозиції.', verbose_name='Опис')),
                ('image', models.ImageField(help_text='Зображення прозорого ноутбука, телефону тощо.', upload_to='promo_banners/', verbose_name='Зображення товару')),
                ('button_text', models.CharField(default='КУПИТИ ЗАРАЗ', max_length=100, verbose_name='Текст кнопки')),
                ('button_class', models.CharField(choices=[('btn-primary', 'Primary (Синій)'), ('btn-info', 'Info (Блакитний)'), ('btn-danger', 'Danger (Червоний)'), ('btn-success', 'Success (Зелений)')], default='btn-primary', max_length=50, verbose_name='Стиль кнопки (Bootstrap)')),
                ('link_url', models.CharField(default='?q=HP+Victus', help_text='URL або пошуковий запит куди веде кнопка.', max_length=255, verbose_name='Посилання для кнопки')),
                ('background_style', models.CharField(default='linear-gradient(135deg, #070c1e 0%, #0d1a3a 100%)', help_text="CSS градієнт для фону картки. Наприклад: 'linear-gradient(135deg, #091a3c 0%, #1e3a8a 100%)'", max_length=300, verbose_name='Стиль фону (CSS Gradient)')),
                ('is_active', models.BooleanField(default=True, help_text='Якщо вимкнено, банер не відображатиметься.', verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, help_text='Сортування від меншого до більшого.', verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Промо банер',
                'verbose_name_plural': 'Промо банери',
                'ordering': ['order', '-id'],
            },
        ),
    ]
