# Generated by Django 4.2.23 on 2026-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_promobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(help_text='Назва картки українською, наприклад: Геймерські ноутбуки', max_length=100, verbose_name='Назва (UA)')),
                ('name_en', models.CharField(help_text='Назва картки англійською, наприклад: Gaming Laptops', max_length=100, verbose_name='Назва (EN)')),
                ('icon', models.CharField(choices=[('bi-laptop', 'Ноутбук (bi-laptop)'), ('bi-laptop-fill', 'Ноутбук заповнений (bi-laptop-fill)'), ('bi-pc-display', 'Монітор (bi-pc-display)'), ('bi-mouse', 'Миша (bi-mouse)'), ('bi-phone', 'Телефон (bi-phone)'), ('bi-headphones', 'Навушники (bi-headphones)'), ('bi-keyboard', 'Клавіатура (bi-keyboard)'), ('bi-cpu', 'Процесор (bi-cpu)'), ('bi-hdd', 'Диск (bi-hdd)'), ('bi-printer', 'Принтер (bi-printer)'), ('bi-camera', 'Камера (bi-camera)'), ('bi-controller', 'Геймпад (bi-controller)'), ('bi-smartwatch', 'Розумний годинник (bi-smartwatch)'), ('bi-tablet', 'Планшет (bi-tablet)')], default='bi-laptop', max_length=50, verbose_name='Bootstrap іконка')),
                ('gradient', models.CharField(choices=[('linear-gradient(135deg, #1e293b 0%, #0f172a 100%)', 'Темно-синій'), ('linear-gradient(135deg, #4c1d95 0%, #1e1b4b 100%)', 'Фіолетовий'), ('linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)', 'Блакитний'), ('linear-gradient(135deg, #4b5563 0%, #1f2937 100%)', 'Сірий'), ('linear-gradient(135deg, #065f46 0%, #022c22 100%)', 'Зелений'), ('linear-gradient(135deg, #7f1d1d 0%, #450a0a 100%)', 'Червоний')], default='linear-gradient(135deg, #1e293b 0%, #0f172a 100%)', max_length=200, verbose_name='CSS градієнт фону')),
                ('border_color', models.CharField(choices=[('rgba(59, 130, 246, 0.15)', 'Синій'), ('rgba(139, 92, 246, 0.15)', 'Фіолетовий'), ('rgba(14, 165, 233, 0.15)', 'Блакитний'), ('rgba(156, 163, 175, 0.15)', 'Сірий'), ('rgba(52, 211, 153, 0.15)', 'Зелений'), ('rgba(248, 113, 113, 0.15)', 'Червоний')], default='rgba(59, 130, 246, 0.15)', max_length=60, verbose_name='Колір рамки')),
                ('hover_shadow', models.CharField(default='rgba(59, 130, 246, 0.2)', help_text='Колір тіні картки при наведенні, наприклад: rgba(59, 130, 246, 0.2)', max_length=80, verbose_name='Тінь при hover')),
                ('search_query', models.CharField(help_text='Запит для кнопки, наприклад: геймер або ultrabook. Формується як ?q=...', max_length=200, verbose_name='Пошуковий запит')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('categories', models.ManyToManyField(blank=True, help_text='Товари з цих категорій потраплять до цього блоку при перегляді', related_name='trending_cards', to='products.category', verbose_name="Прив'язані категорії")),
            ],
            options={
                'verbose_name': 'Актуальна категорія',
                'verbose_name_plural': 'Актуальні категорії',
                'ordering': ['order', 'id'],
            },
        ),
    ]
